version: "3.9"

volumes:
  db-store:
  localstack-store:

services:
  backend:
    build:
      context: .
      dockerfile: ./infra/docker/backend/Dockerfile
      target: development
    volumes:
      - "./backend:/app"
    ports:
      - "8081:3000"
  db:
    build:
      context: .
      dockerfile: ./infra/docker/db/Dockerfile
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hono_tutorial
  mailhog:
    image: mailhog/mailhog
    ports:
      - target: 8025
        published: 8025
        protocol: tcp
        mode: host
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - target: 4566
        published: 4566
        protocol: tcp
        mode: host
    volumes:
      - ./infra/docker/localstack/scripts:/etc/localstack/init/ready.d
      - localstack-store:/var/lib/localstack
  frontend:
    build:
      context: .
      dockerfile: ./infra/docker/frontend/Dockerfile
    volumes:
      - "./frontend:/app"
    ports:
      - "5173:5173"